// <auto-generated />
using System;
using HealthBloggie.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthBloggie.Web.Migrations
{
  //  [DbContext(typeof(BloggieDbContext))]
   // [Migration("20250403113105_InitialN Migrations")]
    partial class InitialNMigrations
    {
        /// <inheritdoc />
     
    }
}
